/* tslint:disable */
require("./HomeView.module.css");
const styles = {
  reveal: 'reveal_86a5ceab',
  revealVisible: 'revealVisible_86a5ceab',
  homeContainer: 'homeContainer_86a5ceab',
  premiumBanner: 'premiumBanner_86a5ceab',
  bannerContent: 'bannerContent_86a5ceab',
  badge: 'badge_86a5ceab',
  bannerTitle: 'bannerTitle_86a5ceab',
  bannerSubtitle: 'bannerSubtitle_86a5ceab',
  slideBanner: 'slideBanner_86a5ceab',
  primaryButton: 'primaryButton_86a5ceab',
  bannerImage: 'bannerImage_86a5ceab',
  aiGlow: 'aiGlow_86a5ceab',
  cardsGrid: 'cardsGrid_86a5ceab',
  clockCard: 'clockCard_86a5ceab',
  ratingCard: 'ratingCard_86a5ceab',
  cardBgIcon: 'cardBgIcon_86a5ceab',
  on: 'on_86a5ceab',
  off: 'off_86a5ceab',
  clockIcon: 'clockIcon_86a5ceab',
  ratingIcon: 'ratingIcon_86a5ceab',
  label: 'label_86a5ceab',
  hint: 'hint_86a5ceab',
  time: 'time_86a5ceab',
  ratingValueRow: 'ratingValueRow_86a5ceab',
  ratingValue: 'ratingValue_86a5ceab',
  ratingMax: 'ratingMax_86a5ceab',
  logsSection: 'logsSection_86a5ceab',
  ongoingCard: 'ongoingCard_86a5ceab',
  gradientMove: 'gradientMove_86a5ceab',
  floatingShadow: 'floatingShadow_86a5ceab',
  jobHeader: 'jobHeader_86a5ceab',
  jobStatus: 'jobStatus_86a5ceab',
  rotateIcon: 'rotateIcon_86a5ceab',
  spin: 'spin_86a5ceab',
  priorityHigh: 'priorityHigh_86a5ceab',
  priorityMedium: 'priorityMedium_86a5ceab',
  priorityLow: 'priorityLow_86a5ceab',
  jobTitle: 'jobTitle_86a5ceab',
  jobDescription: 'jobDescription_86a5ceab',
  jobFooter: 'jobFooter_86a5ceab',
  startTime: 'startTime_86a5ceab',
  openJobBtn: 'openJobBtn_86a5ceab',
  inProgressImage: 'inProgressImage_86a5ceab',
  logsHeader: 'logsHeader_86a5ceab',
  historyBtn: 'historyBtn_86a5ceab',
  logsList: 'logsList_86a5ceab',
  logCard: 'logCard_86a5ceab',
  logIcon: 'logIcon_86a5ceab',
  green: 'green_86a5ceab',
  blue: 'blue_86a5ceab',
  logContent: 'logContent_86a5ceab',
  logHeader: 'logHeader_86a5ceab',
  logType: 'logType_86a5ceab',
  activityTime: 'activityTime_86a5ceab',
  logDescription: 'logDescription_86a5ceab',
  trustBanner: 'trustBanner_86a5ceab',
  trustContent: 'trustContent_86a5ceab',
  trustIcon: 'trustIcon_86a5ceab',
  chatBot_Container: 'chatBot_Container_86a5ceab'
};

export default styles;
/* tslint:enable */